import { useState } from 'react'
import type { Report } from './ProjectApp'
import ModelComparison from './ModelComparison'
import remediation from './config/audit-remediation.json'
import './ProjectApp.css'
import './CurrentAuditApp.css'

const fmt = (n: number, digits = 0) => n.toLocaleString('en-GB', { maximumFractionDigits: digits })
const titles = ['Inventory field semantics', 'Arrival timestamps', 'Legacy duration units', 'Snapshot coverage', 'Occupancy forecasts and alerts', 'Model and feature provenance', 'Feature availability and issue time', 'Saved models and reload checks', 'Station identity and missingness', 'Station ID crosswalk', 'Evaluation coverage', 'Seasonal baseline alignment', 'Environment reproducibility', 'Documentation coverage', 'Legacy implementation overlap', 'SDK and chart contracts', 'Model metric provenance', 'Local artifact storage', 'Evidence versioning', 'Database integration', 'Recorded usage and weather', 'Nonnegative forecast outputs', 'Validation checks']
const label = (status: string) => status === 'Resolved in rebuild' ? 'Verified scope' : status === 'Partial' ? 'Limited scope' : 'Open limitation'
export default function CurrentAuditApp({ report, view }: { report: Report; view: 'overview' | 'model' | 'findings' }) {
  const [horizon, setHorizon] = useState(60)
  const [filter, setFilter] = useState('All')
  const [search, setSearch] = useState('')
  const findings = remediation.findings.map(item => ({ ...item, title: titles[Number(item.id.slice(1)) - 1] }))
  const visible = findings.filter(item => (filter === 'All' || label(item.status) === filter) && `${item.id} ${item.title} ${item.detail}`.toLowerCase().includes(search.toLowerCase()))
  const model = report.models.find(item => item.horizon_minutes === horizon)!
  return <div className="project-app current-audit audit-panels">
    {view === 'overview' && <><div className="project-kpis"><article><span>Recorded departures · {report.year}</span><strong>{fmt(report.departures)}</strong><small>{fmt(report.arrivals)} arrivals</small></article><article><span>Model cohort</span><strong>{report.modeled_stations} stations</strong><small>{report.observed_stations} observed source IDs</small></article><article><span>Historical weather</span><strong>{fmt(report.weather.hours)} hours</strong><small>Open-Meteo / Copernicus ERA5</small></article><article><span>Selected +60m model</span><strong>{model.selected_model}</strong><small>Test MAE {fmt(model.metrics.find(m => m.selected)!.mae, 4)}</small></article></div>
    <div className="weather-grid audit-overview-cards"><article className="project-card"><h2>Departure forecasting</h2><p>Ten candidates evaluated on identical chronological splits. Models within 1% of the best validation MAE enter a simplicity tie-break. Selected models: {report.models.map(model => `+${model.horizon_minutes}m ${model.selected_model}`).join('; ')}.</p><a className="project-link" href="#model">Compare models →</a><p>Departure counts do not represent bikes available. Inventory forecasts and predicted empty/full alerts are not available.</p></article><article className="project-card"><h2>Rain and recorded usage</h2><p>{fmt(Math.abs(report.association.adjusted_change_pct), 2)}% {report.association.adjusted_change_pct < 0 ? 'fewer' : 'more'} departures in rainy hours compared with calendar-matched dry hours across the year.</p><a className="project-link" href="#weather">Inspect monthly results and sample sizes →</a><p>Association only. Weather reanalysis is excluded from forecast inputs.</p></article></div><p className="project-footnote">Trip reference year: {report.year}. Inventory observations cover a separate historical period. Evidence generated {report.generated_at.slice(0,10)}. Forecasts are historical research outputs, not a live availability service.</p></>}
    {view === 'model' && <><div className="project-controls"><label>Forecast horizon<select value={horizon} onChange={event => setHorizon(Number(event.target.value))}>{report.models.map(item => <option key={item.horizon_minutes} value={item.horizon_minutes}>+{item.horizon_minutes} minutes</option>)}</select></label></div><ModelComparison model={model} /><a className="project-link" href="#replay">Explore selected-model predictions →</a></>}
    {view === 'findings' && <><p>Assessment reviewed {remediation.reviewed_at}. Scope: {remediation.scope}.</p><div className="project-controls"><label>Assessment scope<select value={filter} onChange={event => setFilter(event.target.value)}>{['All','Verified scope','Limited scope','Open limitation'].map(status => <option key={status}>{status}</option>)}</select></label><label>Search assessment<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Weather, models, A08…" /></label><p aria-live="polite">{visible.length} of {findings.length} topics</p></div>{visible.map(item => <details className="project-card audit-remediation" key={item.id}><summary><span className="project-eyebrow">{item.id}</span><span>{item.title}</span><span className="project-badge">{label(item.status)}</span></summary><p>{item.detail}</p><p className="project-footnote"><strong>Evidence:</strong> {item.evidence}</p></details>)}<details className="project-card"><summary>Assumptions and limitations</summary><ol>{report.assumptions.map(item => <li key={item}>{item}</li>)}</ol></details><a className="project-link" href="/project-data/report.json" download>Download evidence JSON ↓</a></>}
  </div>
}
